name: Build AntSimulation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.compiler || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.28.3'

    - name: Set up Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: |
        chmod +x setup_linux_dependencies.sh
        ./setup_linux_dependencies.sh
        
        # Install Clang if needed
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get update
          sudo apt-get install -y clang
        fi

    - name: Add MSBuild to PATH
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: List Build Output
      run: |
        echo "Binaries in:"
        ls -R build/bin || dir build\\bin

    - name: Display SHA256 hash (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "Generated build verification hash:"
        cat build/build_verification.txt || echo "Hash not found."

    - name: Display SHA256 hash (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Generated build verification hash:"
        type build\build_verification.txt || echo "Hash not found."

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AntSimulation-${{ matrix.os }}${{ matrix.compiler && format('-{0}', matrix.compiler) || '' }}
        path: build/bin/*

    - name: Upload Build Hash
      uses: actions/upload-artifact@v4
      with:
        name: BuildHash-${{ matrix.os }}${{ matrix.compiler && format('-{0}', matrix.compiler) || '' }}
        path: |
          build/build_verification.txt
